/* summary-styles.js */

import {Dimensions, Image, StyleSheet} from 'react-native';

const { width, height } = Dimensions.get('window');

const summaryStyles = StyleSheet.create({
	container: {
		alignItems: 'center',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
		backgroundColor: '#000',
		position: 'relative',
		paddingBottom: 5,
	},
	homeToolbar: {
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		height: 56,
	},
	scrollContainer: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		width: width,
	},
	summaryHeader: {
		fontSize: 24,
		fontWeight: '700',
		marginBottom: 16,
		textAlign: 'center',
	},
	summaryButton: {
		width: 130,
		backgroundColor: '#c4b301',
		elevation: 1.5,
		height: 50,
		alignItems: 'center',
		alignSelf: 'flex-end',
		justifyContent: 'center',
	},
	summaryButtonText: {
		color: '#fff',
		fontSize: 22,
		textAlign: 'center',
		textAlignVertical: 'center',
	},
	boldLabel: {
		fontWeight: '700',
	},
	sidebar: {
		alignItems: 'flex-start',
		backgroundColor: '#dbd8da',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
	},
	closeButton: {
		margin: 8,
		position: 'absolute',
		top: 0,
		right: 8,
	},
	sbProfileName: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#262426',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 8,
		paddingTop: 16,
		paddingBottom: 16,
	},
	sbProfileText: {
		color: '#dbd8da',
		fontSize: 18,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbFeaturedContent: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		borderTopWidth: 1,
		borderTopColor: '#96afd1',
		borderBottomWidth: 1,
		borderBottomColor: '#444',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		padding: 8,
		paddingBottom: 16,
	},
	sbHeader: {
		color: '#fff',
		fontSize: 16,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbSubHeader: {
		color: '#fff',
		fontSize: 14,
		fontWeight: '100',
		marginLeft: 8,
	},
	menuButton: {
		position: 'absolute',
		top: 10,
		left: 10,
	},
	menuItems: {
		flex: 6,
		flexDirection: 'column',
	},
	menuItem: {
		alignSelf: 'stretch',
		padding: 16,
	},
	menuHeader: {
		color: '#262426',
		fontSize: 28,
		fontWeight: '100',
	},
	menuLabel: {
		color: '#262426',
		fontSize: 18,
		fontWeight: '100',
	},
	sbFooter: {
		alignSelf: 'stretch',
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: '#262426',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 16,
	},
	versionText: {
		alignSelf: 'flex-end',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		bottom: 12,
		right: 12,
		color: '#262426',
		position: 'absolute',
		fontSize: 12,
		opacity: 0.75,
	},
	primaryText: {
		color: '#fff',
		fontSize: 40,
		fontWeight: '700',
		textAlign: 'center',
	},
	secondaryText: {
		color: '#fff',
		fontSize: 20,
		fontWeight: '100',
		textAlign: 'center',
	},
	headerContainer: {
		backgroundColor: '#000',
		width: width,
		height: 90,
		maxHeight: 90,
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		paddingTop: 10,
		paddingBottom: 10,
	},
	contentContainer: {
		flex: 2,
		flexDirection: 'column',
		backgroundColor: '#000',
	},
	playerBuildContainer: {
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		alignItems: 'flex-start',
	},
	itemHeader: {
		fontSize: 14,
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
		borderBottomWidth: 1,
		borderBottomColor: '#fff',
		paddingBottom: 4,
	},
	skillContainer: {
		flexDirection: 'column',
	},
	skillItem: {
		marginBottom: 5,
	},
	skillImage: {
		alignItems: 'center',
		justifyContent: 'center',
		alignSelf: 'center',
	},
	skillText: {
		color: '#fff',
		fontSize: 12,
		textAlign: 'center',
		alignSelf: 'center',
		height: 32,
	},
	positionText: {
		fontSize: 32,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
	},
	badgeName: {
		height: 32,
		marginTop: 5,
		marginBottom: 5,
		paddingRight: 5,
		paddingLeft: 5,
		textAlignVertical: 'center'
	},
	playerContainer: {
		justifyContent: 'flex-start',
		alignItems: 'flex-start',
		position: 'relative',
	},
	buildAvatar: {
		alignItems: 'flex-start',
		opacity: 0.25,
	},
	badgeContainer: {
		justifyContent: 'center',
		alignItems: 'center',
	},
	badgePanel: {
		position: 'relative',
	},
	badgeItem: {
		position: 'relative',
		height: 82,
		marginBottom: 2.5,
		alignItems: 'center',
		justifyContent: 'center',
	},
	badgeImageContainer: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'center',
		alignItems: 'center',
	},
	badgeText: {
		fontSize: 32,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		textAlignVertical: 'center',
		alignSelf: 'center',
		flex: 1,
		paddingTop: -7.5,
		textShadowColor: '#222',
		textShadowOffset: { width: 0.5, height: 0.5 },
		textShadowRadius: 1,
	},
	badgeImage: {
		alignItems: 'center',
		justifyContent: 'center',
		alignSelf: 'center',
		flex: 1,
	},
	summaryContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'stretch',
		justifyContent: 'center',
		position: 'relative',
	},
	playerAttributeContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'stretch',
		justifyContent: 'center',
		flexWrap: 'wrap',
		paddingLeft: 10,
		paddingRight: 10,
	},
	badgesContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'stretch',
		justifyContent: 'flex-start',
		flexWrap: 'wrap',
		paddingTop: 20,
	},
	capsContainer: {
		flex: 1,
		flexDirection: 'column',
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
	},
	filterContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'flex-start',
		justifyContent: 'center',
		flexWrap: 'nowrap',
		alignSelf: 'flex-start',
	},
	filterItem: {
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'flex-start',
		borderBottomWidth: 1,
		borderBottomColor: '#fff',
	},
	filterText: {
		fontSize: 20,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		width: 60,
	},
	attributeItem: {
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
	},
	attributeItemBorder: {
		borderBottomWidth: 1,
		borderBottomColor: '#fff',
	},
	attributeText: {
		fontSize: 40,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
	},
	attributeName: {
		fontSize: 14,
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
		paddingBottom: 0,
		marginBottom: 4,
	},
});

export default summaryStyles;
