/* compare-styles.js */

import {Dimensions, Image, StyleSheet} from 'react-native';

const compareStyles = StyleSheet.create({
	container: {
		alignItems: 'center',
		backgroundColor: '#000',
		justifyContent: 'center',
		flex: 1,
		flexDirection: 'column',
		padding: 20,
		paddingBottom: 0,
	},
	scrollContainer: {
		flexDirection: 'column',
	},
	compareSplashContainer: {
		flexDirection: 'column',
		flexWrap: 'nowrap',
		alignSelf: 'center',
	},
	compareSplash: {
		alignItems: 'flex-start',
		resizeMode: Image.resizeMode.contain,
		justifyContent: 'flex-start',
		alignSelf: 'center',
		height: 340,
		opacity: 0.5,
	},
	sidebar: {
		alignItems: 'flex-start',
		backgroundColor: '#dbd8da',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
	},
	sbProfileName: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#262426',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 8,
		paddingTop: 16,
		paddingBottom: 16,
	},
	sbProfileText: {
		color: '#dbd8da',
		fontSize: 18,
		fontWeight: '100',
		marginLeft: 8,
	},
	menuButton: {
		position: 'absolute',
		top: 10,
		left: 10,
		zIndex: 100,
	},
	menuItems: {
		flex: 6,
		flexDirection: 'column',
	},
	menuItem: {
		alignSelf: 'stretch',
		padding: 16,
	},
	menuHeader: {
		color: '#262426',
		fontSize: 28,
		fontWeight: '100',
	},
	menuLabel: {
		color: '#262426',
		fontSize: 18,
		fontWeight: '100',
	},
	sbFooter: {
		alignSelf: 'stretch',
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: '#262426',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 16,
	},
	versionText: {
		alignSelf: 'flex-end',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		bottom: 12,
		right: 12,
		color: '#262426',
		position: 'absolute',
		fontSize: 12,
		opacity: 0.75,
	},
	addArchetype: {
		flex: 1,
		flexDirection: 'row',
		alignSelf: 'flex-end',
		justifyContent: 'center',
		alignItems: 'center',
		height: 72,
		padding: 10,
		borderWidth: 1,
		borderColor: '#262426',
		backgroundColor: '#BF1725',
		paddingRight: 10,
	},
	addArchetypeIcon: {
		alignItems: 'flex-start',
		resizeMode: Image.resizeMode.contain,
		justifyContent: 'flex-start',
		alignSelf: 'center',
		marginRight: 10,
	},
	addArchetypeText: {
		color: '#fff',
		fontSize: 18,
		fontWeight: '100',
		textAlign: 'center',
	},
	primaryText: {
		color: '#fff',
		fontSize: 40,
		fontWeight: '700',
		textAlign: 'center',
	},
	secondaryText: {
		color: '#fff',
		fontSize: 20,
		fontWeight: '100',
		textAlign: 'center',
	},
	headerContainer: {
		backgroundColor: '#000',
		height: 91,
		maxHeight: 91,
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 25,
	},
	contentContainer: {
		flex: 2,
		flexDirection: 'row',
		backgroundColor: '#000',
	},
	comparatorTable: {
		alignItems: 'flex-start',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		flexWrap: 'nowrap',
	},
});

export default compareStyles;
