/* compare-styles.js */

import {Image, StyleSheet} from 'react-native';

const compareStyles = StyleSheet.create({
	container: {
		alignItems: 'center',
		backgroundColor: '#000',
		justifyContent: 'center',
		flex: 1,
		flexDirection: 'column',
		padding: 10,
		paddingBottom: 25,
	},
	homeToolbar: {
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		height: 56,
	},
	scrollContainer: {
		flexDirection: 'row',
		flexWrap: 'wrap',
	},
	compareHeader: {
		fontSize: 24,
		fontWeight: '700',
		marginBottom: 16,
		textAlign: 'center',
	},
	compareButton: {
		width: 130,
		backgroundColor: '#c4b301',
		elevation: 1.5,
		height: 50,
		alignItems: 'center',
		alignSelf: 'flex-end',
		justifyContent: 'center',
	},
	compareButtonText: {
		color: '#fff',
		fontSize: 22,
		textAlign: 'center',
		textAlignVertical: 'center',
	},
	boldLabel: {
		fontWeight: '700',
	},
	sidebar: {
		alignItems: 'flex-start',
		backgroundColor: '#dbd8da',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
	},
	closeButton: {
		margin: 8,
		position: 'absolute',
		top: 0,
		right: 8,
	},
	sbProfileName: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#262426',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 8,
		paddingTop: 16,
		paddingBottom: 16,
	},
	sbProfileText: {
		color: '#dbd8da',
		fontSize: 18,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbFeaturedContent: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		borderTopWidth: 1,
		borderTopColor: '#96afd1',
		borderBottomWidth: 1,
		borderBottomColor: '#444',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		padding: 8,
		paddingBottom: 16,
	},
	sbHeader: {
		color: '#fff',
		fontSize: 16,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbSubHeader: {
		color: '#fff',
		fontSize: 14,
		fontWeight: '100',
		marginLeft: 8,
	},
	menuButton: {
		position: 'absolute',
		top: 10,
		left: 10,
		zIndex: 100,
	},
	menuItems: {
		flex: 6,
		flexDirection: 'column',
	},
	menuItem: {
		alignSelf: 'stretch',
		padding: 16,
	},
	menuHeader: {
		color: '#262426',
		fontSize: 28,
		fontWeight: '100',
	},
	menuLabel: {
		color: '#262426',
		fontSize: 18,
		fontWeight: '100',
	},
	sbFooter: {
		alignSelf: 'stretch',
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: '#262426',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 16,
	},
	versionText: {
		alignSelf: 'flex-end',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		bottom: 12,
		right: 12,
		color: '#262426',
		position: 'absolute',
		fontSize: 12,
		opacity: 0.75,
	},
	addArchetype: {
		flex: 1,
		flexDirection: 'row',
		alignSelf: 'flex-end',
		justifyContent: 'center',
		alignItems: 'center',
		height: 72,
		padding: 10,
		borderWidth: 1,
		borderColor: '#262426',
		backgroundColor: '#BF1725',
		paddingRight: 10,
	},
	addArchetypeIcon: {
		alignItems: 'flex-start',
		resizeMode: Image.resizeMode.contain,
		justifyContent: 'flex-start',
		alignSelf: 'center',
		marginRight: 10,
	},
	addArchetypeText: {
		color: '#fff',
		fontSize: 18,
		fontWeight: '100',
		textAlign: 'center',
	},
	primaryText: {
		color: '#fff',
		fontSize: 40,
		fontWeight: '700',
		textAlign: 'center',
	},
	secondaryText: {
		color: '#fff',
		fontSize: 20,
		fontWeight: '100',
		textAlign: 'center',
	},
	headerContainer: {
		backgroundColor: '#000',
		height: 91,
		maxHeight: 91,
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 25,
	},
	contentContainer: {
		flex: 2,
		flexDirection: 'row',
		backgroundColor: '#000',
	},
	playerBuildContainer: {
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'stretch',
	},
	itemHeader: {
		fontSize: 14,
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
		borderBottomWidth: 1,
		borderBottomColor: '#fff',
		paddingBottom: 4,

	},
	skillContainer: {
		flex: 1.5,
	},
	skillItem: {
		marginBottom: 10,
		paddingLeft: 5,
		paddingRight: 5,
	},
	skillText: {
		color: '#fff',
		fontSize: 12,
		textAlign: 'center',
		alignSelf: 'center',
	},
	playerContainer: {
		flex: 3,
	},
	buildAvatar: {
		alignItems: 'flex-start',
		resizeMode: Image.resizeMode.contain,
		justifyContent: 'flex-start',
		alignSelf: 'center',
		flex: 1,
		opacity: 0.25,
	},
	badgeContainer: {
		flex: 1.5,
		justifyContent: 'flex-end'
	},
	badgePanel: {

	},
	badgeItem: {
		position: 'relative',
	},
	badgeText: {
		fontSize: 32,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
	},
	badgeImage: {

	},
	compareContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'stretch',
		justifyContent: 'center',
		position: 'relative',
	},
	playerAttributeContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'stretch',
		justifyContent: 'center',
		flexWrap: 'wrap',
		paddingLeft: 10,
		paddingRight: 10,
	},
	attributeItem: {
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		borderBottomWidth: 1,
		borderBottomColor: '#fff',
	},
	attributeText: {
		fontSize: 32,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
	},
	attributeName: {
		fontSize: 14,
		color: '#fff',
		textAlign: 'center',
		alignSelf: 'center',
		paddingBottom: 0,
		marginBottom: 4,
	},
});

export default compareStyles;
