/* browser-styles.js */

import {Image, StyleSheet} from 'react-native';

const browserStyles = StyleSheet.create({
	container: {
		alignItems: 'center',
		backgroundColor: '#000',
		justifyContent: 'center',
		flex: 1,
		flexDirection: 'column',
		paddingBottom: 25,
	},
	scrollContainer: {
		flexDirection: 'column',
	},
	sidebar: {
		alignItems: 'flex-start',
		backgroundColor: '#dbd8da',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
	},
	closeButton: {
		margin: 8,
		position: 'absolute',
		top: 0,
		right: 8,
	},
	sbProfileName: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#262426',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 8,
		paddingTop: 16,
		paddingBottom: 16,
	},
	sbProfileText: {
		color: '#dbd8da',
		fontSize: 18,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbFeaturedContent: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		borderTopWidth: 1,
		borderTopColor: '#96afd1',
		borderBottomWidth: 1,
		borderBottomColor: '#444',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		padding: 8,
		paddingBottom: 16,
	},
	sbHeader: {
		color: '#fff',
		fontSize: 16,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbSubHeader: {
		color: '#fff',
		fontSize: 14,
		fontWeight: '100',
		marginLeft: 8,
	},
	menuButton: {
		position: 'absolute',
		top: 10,
		left: 10,
		zIndex: 100,
	},
	menuItems: {
		flex: 6,
		flexDirection: 'column',
	},
	menuItem: {
		alignSelf: 'stretch',
		padding: 16,
	},
	menuHeader: {
		color: '#262426',
		fontSize: 28,
		fontWeight: '100',
	},
	menuLabel: {
		color: '#262426',
		fontSize: 18,
		fontWeight: '100',
	},
	sbFooter: {
		alignSelf: 'stretch',
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: '#262426',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 16,
	},
	versionText: {
		alignSelf: 'flex-end',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		bottom: 12,
		right: 12,
		color: '#262426',
		position: 'absolute',
		fontSize: 12,
		opacity: 0.75,
	},
	primaryText: {
		color: '#fff',
		fontSize: 40,
		fontWeight: '700',
		textAlign: 'center',
	},
	secondaryText: {
		color: '#fff',
		fontSize: 20,
		fontWeight: '100',
		textAlign: 'center',
	},
	headerContainer: {
		backgroundColor: '#000',
		height: 91,
		maxHeight: 91,
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 25,
	},
	contentContainer: {
		flex: 2,
		flexDirection: 'column',
		backgroundColor: '#000',
	},
	browserContainer: {
		flex: 1,
		flexDirection: 'column',
		alignItems: 'flex-start',
		justifyContent: 'center',
	},
	browserLocalResults: {
		color: '#fff',
		fontSize: 18,
		textAlign: 'left',
		alignSelf: 'flex-start',
		padding: 10,
	},
	buildItem: {
		flex: 1,
		flexDirection: 'column',
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		padding: 10,
	},
	buildPanel: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
	},
	buildType: {
		position: 'relative',
		width: 48,
		height: 78,
		marginRight: 15,
	},
	buildInfo: {
		flex: 1,
		flexDirection: 'column',
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
	},
	buildDescription: {
		flex: 1,
		flexDirection: 'row',
	},
	buildText: {
		color: '#fff',
		fontSize: 14,
		textAlign: 'left',
		alignSelf: 'flex-start',
	},
	buildBadges: {
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
	},
	badgeItem: {
		position: 'relative',
		height: 48,
		width: 29,
		marginRight: 10,
		marginTop: 5,
		marginBottom: 2.5,
		justifyContent: 'center',
		alignItems: 'center',
	},
	badgeText: {
		height: 40,
		fontSize: 24,
		fontWeight: '900',
		color: '#fff',
		textAlign: 'center',
		textAlignVertical: 'center',
		alignSelf: 'center',
		textShadowColor: '#222',
		textShadowOffset: {width: 0.5, height: 0.5},
		textShadowRadius: 1,
	},
	buildIcon: {
		alignItems: 'center',
		resizeMode: Image.resizeMode.contain,
		justifyContent: 'flex-start',
		alignSelf: 'center',
		marginRight: 5,
	},
	buildRule: {
		alignItems: 'center',
		alignSelf: 'center',
		borderBottomWidth: 1,
		borderBottomColor: '#fff',
		marginTop: 10,
		marginBottom: 10,
	}
});

export default browserStyles;
