/* home-styles.js */

import {Image, StyleSheet} from 'react-native';

const homeStyles = StyleSheet.create({
	container: {
		alignItems: 'stretch',
		backgroundColor: '#000',
		justifyContent: 'center',
		flex: 1,
		flexDirection: 'row',
	},
	homeToolbar: {
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		height: 56,
	},
	scrollContainer: {
		flex: 1,
		flexDirection: 'column',
	},
	slideContainer: {
		flex: 1,
		flexWrap: 'wrap',
		flexDirection: 'row',
	},
	searchBarContainer: {
		alignItems: 'center',
		// backgroundColor: '#96afd1',
		backgroundColor: '#f9f9f9',
		borderWidth: 1,
		borderColor: 'rgba(0,0,0,.12)',
		elevation: 2,
		height: 64,
		flex: 0,
		flexDirection: 'row',
		flexBasis: 88,
		flexShrink: 0,
		justifyContent: 'center',
		marginBottom: 10,
		paddingLeft: 6,
		paddingRight: 8,
		shadowColor: '#000',
		shadowOpacity: 0.5,
		shadowOffset: { width: 0.5, height: 0.5 },
		shadowRadius: 1,
	},
	mplplayerLogo: {
		marginRight: 4,
		height: 52,
		width: 52,
	},
	searchBar: {
		backgroundColor: '#fff',
		height: 48,
		marginTop: 20,
		marginBottom: 20,
		flex: 0.75,
		fontSize: 20,
		elevation: 3,
		backgroundColor: 'rgba(255, 255, 255, 1)',
		paddingLeft: 16,
	},
	contentContainer: {
		flex: 4,
	},
	searchContainer: {
		alignItems: 'center',
		backgroundColor: 'transparent',
		justifyContent: 'center',
		flex: 4,
		flexDirection: 'column',
		width: 400,
	},
	wotdCard: {
		borderRadius: 1,
		backgroundColor: '#3e355c',
		flexDirection: 'column',
		height: 148,
		paddingRight: 0,
		paddingLeft: 0,
	},
	wotdBody: {
		flexDirection: 'column',
		height: 148,
		paddingTop: 0,
		paddingRight: 8,
		paddingBottom: 0,
		paddingLeft: 8,
	},
	wotdText: {
		color: '#fff',
		flex: 1,
		fontSize: 32,
		fontWeight: '700',
		lineHeight: 32,
		paddingTop: 8,
		textAlign: 'center',
	},
	wotdCategory: {
		alignSelf: 'flex-end',
		backgroundColor: '#dc5621',
		borderRadius: 2.25,
		color: '#fff',
		height: 26,
		justifyContent: 'center',
		lineHeight: 18,
		marginBottom: 8,
		padding: 4,
		textAlign: 'center',
		textAlignVertical: 'top',
	},
	postText: {
		color: '#fff',
	},
	searchesCard: {
		paddingTop: 0,
		paddingRight: 0,
		paddingBottom: 0,
		paddingLeft: 0,
	},
	searchesBody: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		paddingTop: 16,
		paddingBottom: 16,
	},
	searchesText: {
		color: '#353535',
		flex: 4,
		fontSize: 22,
	},
	searchesCategory: {
		alignSelf: 'center',
		backgroundColor: '#96afd1',
		borderRadius: 2.25,
		color: '#fff',
		flex: 1,
		justifyContent: 'center',
		lineHeight: 18,
		padding: 4,
		textAlign: 'center',
		textAlignVertical: 'top',
	},
	sidebar: {
		alignItems: 'flex-start',
		backgroundColor: '#000',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
	},
	closeButton: {
		margin: 8,
		position: 'absolute',
		top: 0,
		right: 8,
	},
	sbProfileName: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#DBD8DA',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 8,
		paddingTop: 16,
		paddingBottom: 16,
	},
	sbProfileText: {
		color: '#fff',
		fontSize: 18,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbFeaturedContent: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		borderTopWidth: 1,
		borderTopColor: '#96afd1',
		borderBottomWidth: 1,
		borderBottomColor: '#444',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		padding: 8,
		paddingBottom: 16,
	},
	sbHeader: {
		color: '#fff',
		fontSize: 16,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbSubHeader: {
		color: '#fff',
		fontSize: 14,
		fontWeight: '100',
		marginLeft: 8,
	},
	menuItems: {
		flex: 6,
		flexDirection: 'column',
	}
	,
	menuItem: {
		alignSelf: 'stretch',
		padding: 16,
	},
	menuLabel: {
		color: '#fff',
		fontSize: 18,
		fontWeight: '100',
	},
	sbFooter: {
		alignSelf: 'stretch',
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: '#1673C0',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 16,
	},
	versionText: {
		alignSelf: 'flex-end',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		bottom: 12,
		right: 12,
		color: '#fff',
		position: 'absolute',
		fontSize: 12,
		opacity: 0.75,
	}
});

export default homeStyles;
