const badge_icons = {
	"Acrobat": "dnf",
	"Ankle Breaker": "pnbh",
	"Break Starter": "pnbh",
	"Brick Wall": "athleticism",
	"Bruiser": "athleticism",
	"Catch & Shoot": "shooting",
	"Charge Card": "def",
	"Chase Down Artist": "def",
	"Corner Specialist": "shooting",
	"Deep Range Deadeye": "shooting",
	"Defensive Stopper": "def",
	"Difficult Shots": "shooting",
	"Dimer": "pnbh",
	"Drop Stepper": "dnf",
	"Flashy Passer": "pnbh",
	"Free Throw Ace": "shooting",
	"Glue Hands": "pnbh",
	"Hustle Rebounder": "reb",
	"Limitless Range": "shooting",
	"Lob City Finisher": "athleticism",
	"Lob City Passer": "pnbh",
	"Mid Range Deadeye": "shooting",
	"One Man Fast Break": "athleticism",
	"Pick & Popper": "shooting",
	"Pick & Roll Maestro": "pnbh",
	"Pick & Roller": "dnf",
	"Pick Dodger": "def",
	"Pick Pocket": "def",
	"Post Spin Technician": "dnf",
	"Posterizer": "athleticism",
	"Putback King": "dnf",
	"Quick Reflexes": "athleticism",
	"Relentless Finisher": "dnf",
	"Rim Protector": "def",
	"Tear Dropper": "dnf",
	"Tireless Scorer": "shooting",
	"Up & Under Specialist": "dnf",
}

export default badge_icons;

