const pf = {
	"3 Point Shooting": [
		{
			"Archetype": ["Pure", "Stretch Four"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Catch & Shoot (HoF)",
			"Badge": "Corner Specialist (HoF)",
			"Badge": "Pick & Popper (HoF)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"H": 3,
			"G": 5,
			"S": 4,
			"B": 4,
			"T": 16
		},
		{
			"Archetype": ["Two-Way", "Stretch Four"],
			"Secondary Skill": "Defending",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Slashing", "Stretch Four"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Pick & Roller (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 11,
			"T": 26
		},
		{
			"Archetype": ["Playmaking", "Stretch Four"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Post Scoring", "Stretch Four"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 3,
			"T": 19
		},
		{
			"Archetype": ["Shot Creating", "Stretch Four"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"H": 0,
			"G": 9,
			"S": 4,
			"B": 8,
			"T": 21
		},
		{
			"Archetype": ["Rebounding", "Stretch Four"],
			"Secondary Skill": "Rebounding",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Silver)",
			"H": 0,
			"G": 7,
			"S": 10,
			"B": 5,
			"T": 22
		},
	],
	"Defending": [
		{
			"Archetype": ["Sharpshooting", "Rim Protector"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Charge Card (Gold)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Rim Protector (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 9,
			"T": 24
		},
		{
			"Archetype": ["Pure", "Rim Protector"],
			"Secondary Skill": "Defending",
			"Badge": "Defensive Stopper (HoF)",
			"Badge": "Rim Protector (HoF)",
			"Badge": "Chase Down Artist (HoF)",
			"Badge": "Charge Card (HoF)",
			"Badge": "Bruiser (Gold)",
			"H": 4,
			"G": 5,
			"S": 4,
			"B": 4,
			"T": 17
		},
		{
			"Archetype": ["Slashing", "Rim Protector"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Chase Down Artist (HoF)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Rim Protector (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 1,
			"G": 10,
			"S": 4,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Playmaking", "Rim Protector"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Rim Protector (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 7,
			"T": 23
		},
		{
			"Archetype": ["Post Scoring", "Rim Protector"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Bruiser (HoF)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Rim Protector (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"H": 1,
			"G": 6,
			"S": 7,
			"B": 3,
			"T": 17
		},
		{
			"Archetype": ["Rebounding", "Rim Protector"],
			"Secondary Skill": "Rebounding",
			"Badge": "Rim Protector (HoF)",
			"Badge": "Brusier (HoF)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Putback King (Gold)",
			"Badge": "Defensive Stopper (Gold)",
			"H": 2,
			"G": 8,
			"S": 4,
			"B": 2,
			"T": 16
		},
		{
			"Archetype": ["Shot Creating", "Rim Protector"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Rim Protector (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 0,
			"G": 9,
			"S": 6,
			"B": 10,
			"T": 25
		},
	],
	"Driving & Finishing": [
		{
			"Archetype": ["Sharpshooting", "Athletic Finisher"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Pick & Roller (Gold)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 0,
			"G": 8,
			"S": 5,
			"B": 14,
			"T": 27
		},
		{
			"Archetype": ["Two-Way", "Athletic Finisher"],
			"Secondary Skill": "Defending",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "Posterizer (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Pick & Roller (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 2,
			"G": 7,
			"S": 7,
			"B": 4,
			"T": 20
		},
		{
			"Archetype": ["Pure", "Athletic Finisher"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Posterizer (HoF)",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "Pick & Roller (HoF)",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "Putback King (Gold)",
			"H": 4,
			"G": 4,
			"S": 6,
			"B": 7,
			"T": 21
		},
		{
			"Archetype": ["Playmaking", "Athletic Finisher"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Pick & Roller (Gold)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Post Scoring", "Athletic Finisher"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "Pick & Roller (HoF)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 2,
			"G": 7,
			"S": 7,
			"B": 6,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Athletic Finisher"],
			"Secondary Skill": "Rebounding",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "Posterizer (HoF)",
			"Badge": "Pick & Roller (HoF)",
			"Badge": "Putback King (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"H": 4,
			"G": 5,
			"S": 6,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Shot Creating", "Athletic Finisher"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "Pick & Roller (HoF)",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 3,
			"G": 5,
			"S": 7,
			"B": 8,
			"T": 23
		},
	],
	"Post Scoring": [
		{
			"Archetype": ["Sharpshooting", "Post Scorer"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Up & Under Specialist (HoF)",
			"Badge": "Brusier (Gold)",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Brick Wall (Gold)",
			"H": 2,
			"G": 6,
			"S": 6,
			"B": 9,
			"T": 23
		},
		{
			"Archetype": ["Two-Way", "Post Scorer"],
			"Secondary Skill": "Defending",
			"Badge": "Bruiser (HoF)",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Up & Under Specialist (HoF)",
			"Badge": "Brick Wall (Gold)",
			"H": 1,
			"G": 7,
			"S": 9,
			"B": 3,
			"T": 20
		},
		{
			"Archetype": ["Slashing", "Post Scorer"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Brusier (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"H": 1,
			"G": 9,
			"S": 4,
			"B": 8,
			"T": 22,
		},
		{
			"Archetype": ["Playmaking", "Post Scorer"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (HoF)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Brick Wall (Gold)",
			"H": 1,
			"G": 9,
			"S": 5,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Pure", "Post Scorer"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (HoF)",
			"Badge": "Brusier (HoF)",
			"Badge": "Up & Under Specialist (HoF)",
			"Badge": "Brick Wall (Gold)",
			"H": 4,
			"G": 5,
			"S": 2,
			"B": 10,
			"T": 21
		},
		{
			"Archetype": ["Rebounding", "Post Scorer"],
			"Secondary Skill": "Rebounding",
			"Badge": "Brusier (HoF)",
			"Badge": "Brick Wall (HoF)",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"H": 2,
			"G": 7,
			"S": 6,
			"B": 4,
			"T": 19
		},
		{
			"Archetype": ["Shot Creating", "Post Scorer"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Up & Under Specialist (HoF)",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (HoF)",
			"Badge": "Brusier (Gold)",
			"Badge": "Brick Wall (Gold)",
			"H": 1,
			"G": 7,
			"S": 5,
			"B": 12,
			"T": 25
		},
	],
	"Rebounding": [
		{
			"Archetype": ["Sharshooting", "Rebounder"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Brusier (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 9,
			"T": 24
		},
		{
			"Archetype": ["Two-Way", "Rebounder"],
			"Secondary Skill": "Defending",
			"Badge": "Bruiser (HoF)",
			"Badge": "Putback King (HoF)",
			"Badge": "Brick Wall (HoF)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 3,
			"G": 7,
			"S": 5,
			"B": 2,
			"T": 17
		},
		{
			"Archetype": ["Slashing", "Post Scorer"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Putback King (HoF)",
			"Badge": "Hustle Rebounder (HoF)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 2,
			"G": 9,
			"S": 3,
			"B": 6,
			"T": 20
		},
		{
			"Archetype": ["Playmaking", "Rebounder"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Break Starter (HoF)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Brusier (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 1,
			"G": 7,
			"S": 7,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Post Scoring", "Rebounder"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Bruiser (HoF)",
			"Badge": "Brick Wall (HoF)",
			"Badge": "Putback King (HoF)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 3,
			"G": 5,
			"S": 7,
			"B": 4,
			"T": 19
		},
		{
			"Archetype": ["Glass", "Cleaner"],
			"Secondary Skill": "Rebounding",
			"Badge": "Hustle Rebounder (HoF)",
			"Badge": "Break Starter (HoF)",
			"Badge": "Brick Wall (HoF)",
			"Badge": "Bruiser (HoF)",
			"Badge": "Putback King (HoF)",
			"H": 5,
			"G": 4,
			"S": 3,
			"B": 6,
			"T": 18
		},
		{
			"Archetype": ["Shot Creating", "Rebounder"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Putback King (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 22
		},
	],
}

export default pf;