const pg = {
	"3 Point Shooting": [
		{
			"Archetype": ["Pure", "Sharpshooter"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Catch & Shoot (HoF)",
			"Badge": "Deep Range Deadeye (HoF)",
			"Badge": "Limitless Range (HoF)",
			"Badge": "Corner Specialist (HoF)",
			"Badge": "Tireless Scorer (Gold)",
			"H": 4,
			"G": 4,
			"S": 3,
			"B": 6,
			"T": 17
		},
		{
			"Archetype": ["Two-Way", "Sharpshooter"],
			"Secondary Skill": "Defending",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Slashing", "Sharpshooter"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 9,
			"B": 8,
			"T": 24
		},
		{
			"Archetype": ["Playmaking", "Sharpshooter"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 5,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Sharpshooter"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 9,
			"B": 7,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Sharpshooter"],
			"Secondary Skill": "Rebounding",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 7,
			"B": 10,
			"T": 24
		},
		{
			"Archetype": ["Shot Creating", "Sharpshooter"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"H": 0,
			"G": 10,
			"S": 2,
			"B": 10,
			"T": 22
		},
	],
	"Defending": [
		{
			"Archetype": ["Sharpshooting", "Defender"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Charge Card (Gold)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Pick Dodger (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 6,
			"B": 9,
			"T": 23
		},
		{
			"Archetype": ["Lockdown", "Defender"],
			"Secondary Skill": "Defending",
			"Badge": "Defensive Stopper (HoF)",
			"Badge": "Pick Pocket (HoF)",
			"Badge": "Pick Dodger (HoF)",
			"Badge": "Pick Dodger (HoF)",
			"Badge": "Bruiser (Gold)",
			"H": 4,
			"G": 4,
			"S": 4,
			"B": 5,
			"T": 17
		},
		{
			"Archetype": ["Slashing", "Defender"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Pick Dodger (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Posterizer (Gold)",
			"H": 0,
			"G": 11,
			"S": 3,
			"B": 5,
			"T": 19
		},
		{
			"Archetype": ["Playmaking", "Defender"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Pick Dodger (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 4,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Defender"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Bruiser (HoF)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Pick Dodger (Gold)",
			"H": 1,
			"G": 7,
			"S": 6,
			"B": 5,
			"T": 21
		},
		{
			"Archetype": ["Rebounding", "Defender"],
			"Secondary Skill": "Rebounding",
			"Badge": "Bruiser (HoF)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Pick Dodger (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"H": 1,
			"G": 7,
			"S": 6,
			"B": 5,
			"T": 19
		},
		{
			"Archetype": ["Shot Creating", "Defender"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Pick Dodger (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 5,
			"T": 21
		},
	],
	"Driving & Finishing": [
		{
			"Archetype": ["Sharpshooting", "Slasher"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Posterizer (Gold)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Acrobat (Gold)",
			"Badge": "One Man Fast Break (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"H": 0,
			"G": 8,
			"S": 6,
			"B": 12,
			"T": 26
		},
		{
			"Archetype": ["Two-Way", "Slasher"],
			"Secondary Skill": "Defending",
			"Badge": "Posterizer (HoF)",
			"Badge": "Acrobat (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Tear Dropper (Silver)",
			"H": 3,
			"G": 4,
			"S": 9,
			"B": 6,
			"T": 22
		},
		{
			"Archetype": ["Pure", "Slasher"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Posterizer (HoF)",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "Acrobat (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Tear Dropper (Gold)",
			"H": 4,
			"G": 4,
			"S": 3,
			"B": 11,
			"T": 22
		},
		{
			"Archetype": ["Playmaking", "Slasher"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Acrobat (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 2,
			"G": 6,
			"S": 6,
			"B": 7,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Slasher"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "Acrobat (HoF)",
			"Badge": "Posterizer (Gold)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Tear Dropper (Gold)",
			"H": 2,
			"G": 6,
			"S": 5,
			"B": 10,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Playmaker"],
			"Secondary Skill": "Rebounding",
			"Badge": "Posterizer (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Acrobat (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"H": 2,
			"G": 6,
			"S": 6,
			"B": 9,
			"T": 23
		},
		{
			"Archetype": ["Shot Creating", "Slasher"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Acrobat (HoF)",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Posterizer (Gold)",
			"H": 3,
			"G": 6,
			"S": 3,
			"B": 11,
			"T": 23
		},
	],
	"Passing & Ball Handling": [
		{
			"Archetype": ["Sharpshooting", "Playmaker"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 5,
			"T": 22
		},
		{
			"Archetype": ["Two-Way", "Playmaker"],
			"Secondary Skill": "Defending",
			"Badge": "Dimer (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 0,
			"G": 9,
			"S": 6,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Slashing", "Playmaker"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Ankle Breaker (HoF)",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 1,
			"G": 9,
			"S": 5,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Pure", "Playmaker"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Dimer (HoF)",
			"Badge": "Ankle Breaker (HoF)",
			"Badge": "Pick & Roll Maestro (HoF)",
			"Badge": "Lob City Passer (HoF)",
			"Badge": "Flashy Passer (HoF)",
			"H": 5,
			"G": 5,
			"S": 3,
			"B": 6,
			"T": 19
		},
		{
			"Archetype": ["Post Scoring", "Playmaker"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 0,
			"G": 8,
			"S": 10,
			"B": 4,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Playmaker"],
			"Secondary Skill": "Rebounding",
			"Badge": "Dimer (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"H": 0,
			"G": 10,
			"S": 3,
			"B": 9,
			"T": 22
		},
		{
			"Archetype": ["Shot Creating", "Playmaker"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Ankle Breaker (HoF)",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 1,
			"G": 10,
			"S": 4,
			"B": 5,
			"T": 20
		},
	],
	"Shot Creating": [
		{
			"Archetype": ["Sharpshooting", "Shot Creator"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Tireless Scorer (HoF)",
			"Badge": "Difficult Shots (HoF)",
			"Badge": "Mid Range Deadeye (HoF)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 3,
			"G": 5,
			"S": 6,
			"B": 10,
			"T": 24
		},
		{
			"Archetype": ["Two-Way", "Shot Creator"],
			"Secondary Skill": "Defending",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Slashing", "Shot Creator"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Tear Dropper (HoF)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 1,
			"G": 10,
			"S": 1,
			"B": 11,
			"T": 23
		},
		{
			"Archetype": ["Playmaking", "Shot Creator"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Ankle Breaker (HoF)",
			"Badge": "Tireless Scorer (HoF)",
			"Badge": "Difficult Shots (HoF)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"H": 3,
			"G": 5,
			"S": 7,
			"B": 6,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Shot Creator"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Tear Dropper (HoF)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"H": 1,
			"G": 9,
			"S": 4,
			"B": 8,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Shot Creator"],
			"Secondary Skill": "Rebounding",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 0,
			"G": 8,
			"S": 6,
			"B": 12,
			"T": 26
		},
		{
			"Archetype": ["Pure", "Shot Creator"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Mid Range Deadeye (HoF)",
			"Badge": "Tear Dropper (HoF)",
			"Badge": "Tireless Scorer (HoF)",
			"Badge": "Difficult Shots (HoF)",
			"Badge": "Ankle Breaker (Gold)",
			"H": 4,
			"G": 4,
			"S": 4,
			"B": 8,
			"T": 20
		},
	],
}

export default pg;