const sf = {
	"Passing & Ball Handling": [
		{
			"Archetype": ["Pure", "Point Forward"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Dimer (HoF)",
			"Upgradeable Badge 2": "Pick & Roll Maestro (HoF)",
			"Upgradeable Badge 3": "Lob City Passer (HoF)",
			"Upgradeable Badge 4": "Break Starter (HoF)",
			"Upgradeable Badge 5": "Flashy Passer (HoF)",
			"H": 5,
			"G": 5,
			"S": 3,
			"B": 7,
			"T": 20
		},
		{
			"Archetype": ["Shot Creating", "Point Forward"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Dimer (Gold)",
			"Upgradeable Badge 2": "Lob City Passer (Gold)",
			"Upgradeable Badge 3": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 4": "Break Starter (Gold)",
			"Upgradeable Badge 5": "Flashy Passer (Gold)",
			"H": 0,
			"G": 11,
			"S": 4,
			"B": 6,
			"T": 21
		},
		{
			"Archetype": ["Sharpshooting", "Point Forward"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Lob City Passer (Gold)",
			"Upgradeable Badge 2": "Flashy Passer (Gold)",
			"Upgradeable Badge 3": "Dimer (Gold)",
			"Upgradeable Badge 4": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 5": "Break Starter (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 5,
			"T": 22
		},
		{
			"Archetype": ["Slashing", "Point Forward"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Lob City Passer (Gold)",
			"Upgradeable Badge 2": "One Man Fast Break (Gold)",
			"Upgradeable Badge 3": "Dimer (Gold)",
			"Upgradeable Badge 4": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 5": "Break Starter (Gold)",
			"H": 0,
			"G": 10,
			"S": 5,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Two-Way", "Point Forward"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Dimer (Gold)",
			"Upgradeable Badge 2": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 4": "Break Starter (Gold)",
			"Upgradeable Badge 5": "Flashy Passer (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Point Forward"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Break Starter (HoF)",
			"Upgradeable Badge 2": "Lob City Passer (Gold)",
			"Upgradeable Badge 3": "Dimer (Gold)",
			"Upgradeable Badge 4": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 5": "Flashy Passer (Gold)",
			"H": 1,
			"G": 8,
			"S": 6,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Post Scoring", "Point Forward"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 1": "Lob City Passer (Gold)",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 3": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 4": "Break Starter (Gold)",
			"Upgradeable Badge 5": "Flashy Passer (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 6,
			"T": 23
		}
	],
	"Shot Creating": [
		{
			"Archetype": ["Playmaking", "Shot Creator"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Tireless Scorer (HoF)",
			"Upgradeable Badge 2": "Difficult Shots (HoF)",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 4": "Tear Dropper (Gold)",
			"Upgradeable Badge 5": "One Man Fast Break (Silver)",
			"H": 2,
			"G": 5,
			"S": 9,
			"B": 8,
			"T": 24
		},
		{
			"Archetype": ["Sharpshooting", "Shot Creator"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Tireless Scorer (HoF)",
			"Upgradeable Badge 2": "Difficult Shots (HoF)",
			"Upgradeable Badge 3": "Mid Range Deadeye (HoF)",
			"Upgradeable Badge 4": "Tear Dropper (Gold)",
			"Upgradeable Badge 5": "Corner Speacialist (Silver)",
			"H": 3,
			"G": 4,
			"S": 6,
			"B": 11,
			"T": 24
		},
		{
			"Archetype": ["Slashing", "Shot Creator"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Tear Dropper (HoF)",
			"Upgradeable Badge 2": "Tireless Scorer (Gold)",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "Relentless Finisher (Gold)",
			"H": 1,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Shot Creator"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 2": "Tear Dropper (Gold)",
			"Upgradeable Badge 3": "Tireless Scorer (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "One Man Fast Break (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 12,
			"T": 27
		},
		{
			"Archetype": ["Two-Way", "Shot Creator"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 2": "Tear Dropper (Gold)",
			"Upgradeable Badge 3": "Tireless Scorer (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "Defensive Stopper (Silver)",
			"H": 0,
			"G": 7,
			"S": 6,
			"B": 13,
			"T": 26
		},
		{
			"Archetype": ["Post Scoring", "Shot Creator"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 2": "Tear Dropper (Gold)",
			"Upgradeable Badge 3": "Tireless Scorer (Gold)",
			"Upgradeable Badge 1": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "Up & Under Specialist (Gold)",
			"H": 0,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 22
		},
		{
			"Archetype": ["Pure", "Shot Creator"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Mid Range Deadeye (HoF)",
			"Upgradeable Badge 2": "Tear Dropper (HoF)",
			"Upgradeable Badge 3": "Tireless Scorer (HoF)",
			"Upgradeable Badge 4": "Difficult Shots (HoF)",
			"Upgradeable Badge 5": "Relentless Finisher (Silver)",
			"H": 4,
			"G": 3,
			"S": 3,
			"B": 12,
			"T": 22
		},
	],
	"3 Point Shooting": [
		{
			"Archetype": ["Playmaking", "Sharpshooter"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Corner Specialist (Gold)",
			"Upgradeable Badge 2": "Catch & Shoot (Gold)",
			"Upgradeable Badge 3": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 4": "Limitless Range (Gold)",
			"Upgradeable Badge 5": "Pick & Popper (Gold)",
			"H": 0,
			"G": 9,
			"S": 7,
			"B": 7,
			"T": 23
		},
		{
			"Archetype": ["Shot Creating", "Sharpshooter"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Corner Specialist (Gold)",
			"Upgradeable Badge 2": "Catch & Shoot (Gold)",
			"Upgradeable Badge 3": "Pick & Popper (Gold)",
			"Upgradeable Badge 4": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 5": "Deep Range Deadeye (Gold)",
			"H": 0,
			"G": 9,
			"S": 4,
			"B": 8,
			"T": 21
		},
		{
			"Archetype": ["Pure", "Sharpshooter"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Catch & Shoot (HoF)",
			"Upgradeable Badge 2": "Deep Range Deadeye (HoF)",
			"Upgradeable Badge 3": "Limitless Range (HoF)",
			"Upgradeable Badge 4": "Corner Specialist (HoF)",
			"Upgradeable Badge 5": "Pick & Popper (Gold)",
			"H": 4,
			"G": 5,
			"S": 2,
			"B": 6,
			"T": 17
		},
		{
			"Archetype": ["Slashing", "Sharpshooter"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 6,
			"T": 23
		},
		{
			"Archetype": ["Two-Way", "Sharpshooter"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 9,
			"T": 24
		},
		{
			"Archetype": ["Rebounding", "Sharpshooter"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 8,
			"T": 24
		},
		{
			"Archetype": ["Post Scoring", "Sharpshooter"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 6,
			"T": 21
		}
	],
	"Driving & Finishing": [
		{
			"Archetype": ["Playmaking", "Slasher"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "One Man Fast Break (HoF)",
			"Upgradeable Badge 2": "Relentless Finisher (Gold)",
			"Upgradeable Badge 3": "Posterizer (Gold)",
			"Upgradeable Badge 4": "Lob City Finisher (Gold)",
			"Upgradeable Badge 5": "Acrobat (Gold)",
			"H": 1,
			"G": 7,
			"S": 9,
			"B": 7,
			"T": 24
		},
		{
			"Archetype": ["Sharpshooting", "Slasher"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Posterizer (Gold)",
			"Upgradeable Badge 2": "Relentless Finisher (Gold)",
			"Upgradeable Badge 3": "One Man Fast Break (Gold)",
			"Upgradeable Badge 4": "Lob City Finisher (Gold)",
			"Upgradeable Badge 5": "Acrobat (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Rebounding", "Slasher"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Lob City Finisher (HoF)",
			"Upgradeable Badge 2": "Posterizer (HoF)",
			"Upgradeable Badge 3": "One Man Fast Break (HoF)",
			"Upgradeable Badge 4": "Relentless Finisher (Gold)",
			"Upgradeable Badge 5": "Putback King (Gold)",
			"H": 3,
			"G": 6,
			"S": 6,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Two-Way", "Slasher"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 2": "Posterizer (HoF)",
			"Upgradeable Badge 1": "Lob City Finisher (HoF)",
			"Upgradeable Badge 3": "One Man Fast Break (Gold)",
			"Upgradeable Badge 4": "Relentless Finisher (Gold)",
			"Upgradeable Badge 5": "Acrobat (Gold)",
			"H": 2,
			"G": 8,
			"S": 4,
			"B": 6,
			"T": 22
		},
		{
			"Archetype": ["Post Scoring", "Slasher"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 4": "Relentless Finisher (HoF)",
			"Upgradeable Badge 2": "Posterizer (Gold)",
			"Upgradeable Badge 1": "Lob City Finisher (Gold)",
			"Upgradeable Badge 3": "One Man Fast Break (Gold)",
			"Upgradeable Badge 5": "Acrobat (Gold)",
			"H": 1,
			"G": 7,
			"S": 7,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Shot Creating", "Slasher"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 4": "Relentless Finisher (HoF)",
			"Upgradeable Badge 3": "One Man Fast Break (HoF)",
			"Upgradeable Badge 1": "Lob City Finisher (Gold)",
			"Upgradeable Badge 2": "Posterizer (Gold)",
			"Upgradeable Badge 5": "Acrobat (Gold)",
			"H": 2,
			"G": 7,
			"S": 6,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Slasher"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 2": "Posterizer (HoF)",
			"Upgradeable Badge 4": "Relentless Finisher (HoF)",
			"Upgradeable Badge 3": "One Man Fast Break (HoF)",
			"Upgradeable Badge 1": "Lob City Finisher (HoF)",
			"Upgradeable Badge 5": "Acrobat (Gold)",
			"H": 4,
			"G": 5,
			"S": 3,
			"B": 7,
			"T": 19
		},
	],
	"Defending": [
		{
			"Archetype": ["Playmaking", "Defender"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 2": "Charge Card (Gold)",
			"Upgradeable Badge 3": "Pick & Popper (Gold)",
			"Upgradeable Badge 4": "Chase Down Artist (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 11,
			"B": 7,
			"T": 26
		},
		{
			"Archetype": ["Shot Creating", "Defender"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 2": "Chase Down Artist (Gold",
			"Upgradeable Badge 3": "Charge Card (Gold)",
			"Upgradeable Badge 4": "Pick Pocket (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 7,
			"T": 24
		},
		{
			"Archetype": ["Sharpshooting", "Defender"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Charge Card (Gold)",
			"Upgradeable Badge 2": "Defensive Stopper (Gold)",
			"Upgradeable Badge 3": "Pick Pocket (Gold)",
			"Upgradeable Badge 4": "Chase Down Artist (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 9,
			"T": 26
		},
		{
			"Archetype": ["Slashing", "Defender"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Chase Down Artist (HoF)",
			"Upgradeable Badge 2": "Defensive Stopper (Gold)",
			"Upgradeable Badge 3": "Charge Card (Gold)",
			"Upgradeable Badge 4": "Pick Pocket (Gold)",
			"Upgradeable Badge 5": "Posterizer (Gold)",
			"H": 1,
			"G": 9,
			"S": 7,
			"B": 3,
			"T": 20
		},
		{
			"Archetype": ["Rebounding", "Defender"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Bruiser (HoF)",
			"Upgradeable Badge 2": "Chase Down Artist (Gold)",
			"Upgradeable Badge 3": "Defensive Stopper (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 5": "Pick Pocket (Gold)",
			"H": 1,
			"G": 8,
			"S": 7,
			"B": 2,
			"T": 18
		},
		{
			"Archetype": ["Lockdown", "Defender"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 3": "Defensive Stopper (Hof)",
			"Upgradeable Badge 5": "Pick Pocket (HoF)",
			"Upgradeable Badge 2": "Chase Down Artist (HoF)",
			"Upgradeable Badge 4": "Charge Card (HoF)",
			"Upgradeable Badge 1": "Bruiser (Gold)",
			"H": 4,
			"G": 5,
			"S": 4,
			"B": 5,
			"T": 18
		},
		{
			"Archetype": ["Lockdown", "Defender"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Bruiser (Hof)",
			"Upgradeable Badge 3": "Defensive Stopper (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 5": "Pick Pocket (Gold)",
			"Upgradeable Badge 2": "Chase Down Artist (Gold)",
			"H": 1,
			"G": 7,
			"S": 8,
			"B": 6,
			"T": 22
		}
	],
	"Rebounding": [
		{
			"Archetype": ["Playmaking", "Rebounder"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Break Starter (HoF)",
			"Upgradeable Badge 2": "Hustle Rebounder (Gold)",
			"Upgradeable Badge 3": "Brick Wall (Gold)",
			"Upgradeable Badge 4": "Bruiser (Gold)",
			"Upgradeable Badge 5": "Putback King (Gold)",
			"H": 1,
			"G": 7,
			"S": 7,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Sharpshooting", "Rebounder"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Hustle Rebounder (Gold)",
			"Upgradeable Badge 2": "Brick Wall (Gold)",
			"Upgradeable Badge 3": "Break Starter (Gold)",
			"Upgradeable Badge 4": "Bruiser (Gold)",
			"Upgradeable Badge 5": "Putback King (Gold)",
			"H": 0,
			"G": 8,
			"S": 6,
			"B": 11,
			"T": 25
		},
		{
			"Archetype": ["Shot Creating", "Rebounder"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Hustle Rebounder (Gold)",
			"Upgradeable Badge 2": "Putback King (Gold)",
			"Upgradeable Badge 3": "Brick Wall (Gold)",
			"Upgradeable Badge 4": "Break Starter (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 22
		},
		{
			"Archetype": ["Glass", "Cleaner"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Hustle Rebounder (HoF)",
			"Upgradeable Badge 2": "Brick Wall (HoF)",
			"Upgradeable Badge 3": "Break Starter (HoF)",
			"Upgradeable Badge 4": "Bruiser (HoF)",
			"Upgradeable Badge 5": "Putback King (HoF)",
			"H": 5,
			"G": 4,
			"S": 2,
			"B": 8,
			"T": 19
		},
		{
			"Archetype": ["Post Scoring", "Rebounder"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 2": "Brick Wall (HoF)",
			"Upgradeable Badge 4": "Bruiser (HoF)",
			"Upgradeable Badge 1": "Hustle Rebounder (Gold)",
			"Upgradeable Badge 5": "Putback King (Gold)",
			"Upgradeable Badge 3": "Break Starter (Gold)",
			"H": 2,
			"G": 6,
			"S": 5,
			"B": 9,
			"T": 22
		},
		{
			"Archetype": ["Slashing", "Rebounder"],
			"Secondary Skill": "Slashing",
			"Upgradeable Badge 5": "Putback King (HoF)",
			"Upgradeable Badge 1": "Hustle Rebounder (Gold)",
			"Upgradeable Badge 4": "Lob City Finisher (Gold)",
			"Upgradeable Badge 2": "Brick Wall (Gold)",
			"Upgradeable Badge 3": "Break Starter (Gold)",
			"H": 1,
			"G": 10,
			"S": 3,
			"B": 6,
			"T": 20
		},
		{
			"Archetype": ["Two-Way", "Rebounder"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 4": "Bruiser (HoF)",
			"Upgradeable Badge 5": "Putback King (HoF)",
			"Upgradeable Badge 1": "Hustle Rebounder (Gold)",
			"Upgradeable Badge 2": "Brick Wall (Gold)",
			"Upgradeable Badge 3": "Break Starter (Gold)",
			"H": 2,
			"G": 7,
			"S": 7,
			"B": 2,
			"T": 18
		},
	],
	"Post Scoring": [
		{
			"Archetype": ["Playmaking", "Post Scorer"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Post Spin Technician (HoF)",
			"Upgradeable Badge 2": "Drop-Stepper (Gold)",
			"Upgradeable Badge 3": "Bruiser (Gold)",
			"Upgradeable Badge 4": "Up & Under Specialist (Gold)",
			"Upgradeable Badge 5": "Relentless Finisher (Silver)",
			"H": 0,
			"G": 7,
			"S": 7,
			"B": 13,
			"T": 27
		},
		{
			"Archetype": ["Shot Creating", "Post Scorer"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Up & Under Specialist (HoF)",
			"Upgradeable Badge 2": "Post Spin Technician (HoF)",
			"Upgradeable Badge 3": "Drop-Stepper (HoF)",
			"Upgradeable Badge 4": "Bruiser (Gold)",
			"Upgradeable Badge 5": "Brick Wall (Gold)",
			"H": 3,
			"G": 8,
			"S": 4,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Sharpshooting", "Post Scorer"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Up & Under Specialist (Gold)",
			"Upgradeable Badge 2": "Post Spin Technician (Gold)",
			"Upgradeable Badge 3": "Drop-Stepper (Gold)",
			"Upgradeable Badge 4": "Bruiser (Gold)",
			"Upgradeable Badge 5": "Relentless Finisher (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 11,
			"T": 26
		},
		{
			"Archetype": ["Rebounding", "Post Scorer"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Bruiser (HoF)",
			"Upgradeable Badge 2": "Post Spin Technician (Gold)",
			"Upgradeable Badge 3": "Drop-Stepper (Gold)",
			"Upgradeable Badge 4": "Up & Under Specialist (Gold)",
			"Upgradeable Badge 5": "Brick Wall (Gold)",
			"H": 1,
			"G": 7,
			"S": 4,
			"B": 11,
			"T": 23
		},
		{
			"Archetype": ["Slashing", "Post Scorer"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 2": "Post Spin Technician (Gold)",
			"Upgradeable Badge 5": "Relentless Finisher (Gold)",
			"Upgradeable Badge 3": "Drop-Stepper (Gold)",
			"Upgradeable Badge 1": "Bruiser (Gold)",
			"Upgradeable Badge 4": "Up & Under Specialist (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Pure", "Post Scorer"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 2": "Post Spin Technician (HoF)",
			"Upgradeable Badge 3": "Drop-Stepper (HoF)",
			"Upgradeable Badge 1": "Bruiser (HoF)",
			"Upgradeable Badge 4": "Up & Under Specialist (HoF)",
			"Upgradeable Badge 5": "Relentless Finisher (Gold)",
			"H": 4,
			"G": 4,
			"S": 1,
			"B": 15,
			"T": 24
		},
		{
			"Archetype": ["Two-Way", "Post Scorer"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Bruiser (HoF)",
			"Upgradeable Badge 2": "Post Spin Technician (Gold)",
			"Upgradeable Badge 3": "Drop-Stepper (Gold)",
			"Upgradeable Badge 4": "Up & Under Specialist (Gold)",
			"Upgradeable Badge 5": "Defensive Stopper (Silver)",
			"H": 1,
			"G": 6,
			"S": 6,
			"B": 10,
			"T": 23
		}
	]
}

export default sf;