const sf = {
	"3 Point Shooting": [
		{
			"Archetype": ["Pure", "Sharpshooter"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Catch & Shoot (HoF)",
			"Badge": "Deep Range Deadeye (HoF)",
			"Badge": "Limitless Range (HoF)",
			"Badge": "Corner Specialist (HoF)",
			"Badge": "Pick & Popper (Gold)",
			"H": 4,
			"G": 5,
			"S": 2,
			"B": 6,
			"T": 17
		},
		{
			"Archetype": ["Two-Way", "Sharpshooter"],
			"Secondary Skill": "Defending",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 9,
			"T": 24
		},
		{
			"Archetype": ["Slashing", "Sharpshooter"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 6,
			"T": 23
		},
		{
			"Archetype": ["Playmaking", "Sharpshooter"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"H": 0,
			"G": 9,
			"S": 7,
			"B": 7,
			"T": 23
		},
		{
			"Archetype": ["Post Scoring", "Sharpshooter"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 6,
			"T": 21
		},
		{
			"Archetype": ["Rebounding", "Sharpshooter"],
			"Secondary Skill": "Rebounding",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"Badge": "Limitless Range (Gold)",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 8,
			"T": 24
		},
		{
			"Archetype": ["Shot Creating", "Sharpshooter"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Corner Specialist (Gold)",
			"Badge": "Catch & Shoot (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Deep Range Deadeye (Gold)",
			"H": 0,
			"G": 9,
			"S": 4,
			"B": 8,
			"T": 21
		},
	],
	"Defending": [
		{
			"Archetype": ["Sharpshooting", "Defender"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Charge Card (Gold)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 9,
			"T": 26
		},
		{
			"Archetype": ["Lockdown", "Defender"],
			"Secondary Skill": "Defending",
			"Badge": "Defensive Stopper (Hof)",
			"Badge": "Pick Pocket (HoF)",
			"Badge": "Chase Down Artist (HoF)",
			"Badge": "Charge Card (HoF)",
			"Badge": "Bruiser (Gold)",
			"H": 4,
			"G": 5,
			"S": 4,
			"B": 5,
			"T": 18
		},
		{
			"Archetype": ["Slashing", "Defender"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Chase Down Artist (HoF)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Posterizer (Gold)",
			"H": 1,
			"G": 9,
			"S": 7,
			"B": 3,
			"T": 20
		},
		{
			"Archetype": ["Playmaking", "Defender"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick & Popper (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 11,
			"B": 7,
			"T": 26
		},
		{
			"Archetype": ["Post Scoring", "Defender"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Bruiser (Hof)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Chase Down Artist (Gold)",
			"H": 1,
			"G": 7,
			"S": 8,
			"B": 6,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Defender"],
			"Secondary Skill": "Rebounding",
			"Badge": "Bruiser (HoF)",
			"Badge": "Chase Down Artist (Gold)",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"H": 1,
			"G": 8,
			"S": 7,
			"B": 2,
			"T": 18
		},
		{
			"Archetype": ["Shot Creating", "Defender"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Defensive Stopper (Gold)",
			"Badge": "Chase Down Artist (Gold",
			"Badge": "Charge Card (Gold)",
			"Badge": "Pick Pocket (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 7,
			"T": 24
		},
	],
	"Driving & Finishing": [
		{
			"Archetype": ["Sharpshooting", "Slasher"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Posterizer (Gold)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "One Man Fast Break (Gold)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Acrobat (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Two-Way", "Slasher"],
			"Secondary Skill": "Defending",
			"Badge": "Posterizer (HoF)",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "One Man Fast Break (Gold)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Acrobat (Gold)",
			"H": 2,
			"G": 8,
			"S": 4,
			"B": 6,
			"T": 22
		},
		{
			"Archetype": ["Pure", "Slasher"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Posterizer (HoF)",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "Acrobat (Gold)",
			"H": 4,
			"G": 5,
			"S": 3,
			"B": 7,
			"T": 19
		},
		{
			"Archetype": ["Playmaking", "Slasher"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Acrobat (Gold)",
			"H": 1,
			"G": 7,
			"S": 9,
			"B": 7,
			"T": 24
		},
		{
			"Archetype": ["Post Scoring", "Slasher"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "One Man Fast Break (Gold)",
			"Badge": "Acrobat (Gold)",
			"H": 1,
			"G": 7,
			"S": 7,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Slasher"],
			"Secondary Skill": "Rebounding",
			"Badge": "Lob City Finisher (HoF)",
			"Badge": "Posterizer (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 3,
			"G": 6,
			"S": 6,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Shot Creating", "Slasher"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Relentless Finisher (HoF)",
			"Badge": "One Man Fast Break (HoF)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Posterizer (Gold)",
			"Badge": "Acrobat (Gold)",
			"H": 2,
			"G": 7,
			"S": 6,
			"B": 7,
			"T": 22
		},
	],
	"Passing & Ball Handling": [
		{
			"Archetype": ["Sharpshooting", "Point Forward"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 5,
			"T": 22
		},
		{
			"Archetype": ["Two-Way", "Point Forward"],
			"Secondary Skill": "Defending",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Slashing", "Point Forward"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "One Man Fast Break (Gold)",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 0,
			"G": 10,
			"S": 5,
			"B": 8,
			"T": 23
		},
		{
			"Archetype": ["Pure", "Point Forward"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Dimer (HoF)",
			"Badge": "Pick & Roll Maestro (HoF)",
			"Badge": "Lob City Passer (HoF)",
			"Badge": "Break Starter (HoF)",
			"Badge": "Flashy Passer (HoF)",
			"H": 5,
			"G": 5,
			"S": 3,
			"B": 7,
			"T": 20
		},
		{
			"Archetype": ["Post Scoring", "Point Forward"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 6,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Point Forward"],
			"Secondary Skill": "Rebounding",
			"Badge": "Break Starter (HoF)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Dimer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 1,
			"G": 8,
			"S": 6,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Shot Creating", "Point Forward"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Dimer (Gold)",
			"Badge": "Lob City Passer (Gold)",
			"Badge": "Pick & Roll Maestro (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Flashy Passer (Gold)",
			"H": 0,
			"G": 11,
			"S": 4,
			"B": 6,
			"T": 21
		},
	],
	"Post Scoring": [
		{
			"Archetype": ["Sharpshooting", "Post Scorer"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Relentless Finisher (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 11,
			"T": 26
		},
		{
			"Archetype": ["Two-Way", "Post Scorer"],
			"Secondary Skill": "Defending",
			"Badge": "Bruiser (HoF)",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Defensive Stopper (Silver)",
			"H": 1,
			"G": 6,
			"S": 6,
			"B": 10,
			"T": 23
		},
		{
			"Archetype": ["Slashing", "Post Scorer"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Relentless Finisher (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Playmaking", "Post Scorer"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Relentless Finisher (Silver)",
			"H": 0,
			"G": 7,
			"S": 7,
			"B": 13,
			"T": 27
		},
		{
			"Archetype": ["Pure", "Post Scorer"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (HoF)",
			"Badge": "Bruiser (HoF)",
			"Badge": "Up & Under Specialist (HoF)",
			"Badge": "Relentless Finisher (Gold)",
			"H": 4,
			"G": 4,
			"S": 1,
			"B": 15,
			"T": 24
		},
		{
			"Archetype": ["Rebounding", "Post Scorer"],
			"Secondary Skill": "Rebounding",
			"Badge": "Bruiser (HoF)",
			"Badge": "Post Spin Technician (Gold)",
			"Badge": "Drop-Stepper (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"Badge": "Brick Wall (Gold)",
			"H": 1,
			"G": 7,
			"S": 4,
			"B": 11,
			"T": 23
		},
		{
			"Archetype": ["Shot Creating", "Post Scorer"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Up & Under Specialist (HoF)",
			"Badge": "Post Spin Technician (HoF)",
			"Badge": "Drop-Stepper (HoF)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Brick Wall (Gold)",
			"H": 3,
			"G": 8,
			"S": 4,
			"B": 8,
			"T": 23
		},
	],
	"Rebounding": [
		{
			"Archetype": ["Sharpshooting", "Rebounder"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 0,
			"G": 8,
			"S": 6,
			"B": 11,
			"T": 25
		},
		{
			"Archetype": ["Two-Way", "Rebounder"],
			"Secondary Skill": "Defending",
			"Badge": "Bruiser (HoF)",
			"Badge": "Putback King (HoF)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 2,
			"G": 7,
			"S": 7,
			"B": 2,
			"T": 18
		},
		{
			"Archetype": ["Slashing", "Rebounder"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Putback King (HoF)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Lob City Finisher (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 1,
			"G": 10,
			"S": 3,
			"B": 6,
			"T": 20
		},
		{
			"Archetype": ["Playmaking", "Rebounder"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Break Starter (HoF)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Bruiser (Gold)",
			"Badge": "Putback King (Gold)",
			"H": 1,
			"G": 7,
			"S": 7,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Post Scoring", "Rebounder"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Brick Wall (HoF)",
			"Badge": "Bruiser (HoF)",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Putback King (Gold)",
			"Badge": "Break Starter (Gold)",
			"H": 2,
			"G": 6,
			"S": 5,
			"B": 9,
			"T": 22
		},
		{
			"Archetype": ["Glass", "Cleaner"],
			"Secondary Skill": "Rebounding",
			"Badge": "Hustle Rebounder (HoF)",
			"Badge": "Brick Wall (HoF)",
			"Badge": "Break Starter (HoF)",
			"Badge": "Bruiser (HoF)",
			"Badge": "Putback King (HoF)",
			"H": 5,
			"G": 4,
			"S": 2,
			"B": 8,
			"T": 19
		},
		{
			"Archetype": ["Shot Creating", "Rebounder"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Hustle Rebounder (Gold)",
			"Badge": "Putback King (Gold)",
			"Badge": "Brick Wall (Gold)",
			"Badge": "Break Starter (Gold)",
			"Badge": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 22
		},
	],
	"Shot Creating": [
		{
			"Archetype": ["Sharpshooting", "Shot Creator"],
			"Secondary Skill": "3 Point Shooting",
			"Badge": "Tireless Scorer (HoF)",
			"Badge": "Difficult Shots (HoF)",
			"Badge": "Mid Range Deadeye (HoF)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Corner Speacialist (Silver)",
			"H": 3,
			"G": 4,
			"S": 6,
			"B": 11,
			"T": 24
		},
		{
			"Archetype": ["Two-Way", "Shot Creator"],
			"Secondary Skill": "Defending",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Defensive Stopper (Silver)",
			"H": 0,
			"G": 7,
			"S": 6,
			"B": 13,
			"T": 26
		},
		{
			"Archetype": ["Slashing", "Shot Creator"],
			"Secondary Skill": "Driving & Finishing",
			"Badge": "Tear Dropper (HoF)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Relentless Finisher (Gold)",
			"H": 1,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 23
		},
		{
			"Archetype": ["Playmaking", "Shot Creator"],
			"Secondary Skill": "Passing & Ball Handling",
			"Badge": "Tireless Scorer (HoF)",
			"Badge": "Difficult Shots (HoF)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "One Man Fast Break (Silver)",
			"H": 2,
			"G": 5,
			"S": 9,
			"B": 8,
			"T": 24
		},
		{
			"Archetype": ["Post Scoring", "Shot Creator"],
			"Secondary Skill": "Post Scoring",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "Up & Under Specialist (Gold)",
			"H": 0,
			"G": 8,
			"S": 4,
			"B": 10,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Shot Creator"],
			"Secondary Skill": "Rebounding",
			"Badge": "Mid Range Deadeye (Gold)",
			"Badge": "Tear Dropper (Gold)",
			"Badge": "Tireless Scorer (Gold)",
			"Badge": "Difficult Shots (Gold)",
			"Badge": "One Man Fast Break (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 12,
			"T": 27
		},
		{
			"Archetype": ["Pure", "Shot Creator"],
			"Secondary Skill": "Shot Creating",
			"Badge": "Mid Range Deadeye (HoF)",
			"Badge": "Tear Dropper (HoF)",
			"Badge": "Tireless Scorer (HoF)",
			"Badge": "Difficult Shots (HoF)",
			"Badge": "Relentless Finisher (Silver)",
			"H": 4,
			"G": 3,
			"S": 3,
			"B": 12,
			"T": 22
		},
	],
}

export default sf;