const sg = {
	"3 Point Shooting": [
		{
			"Archetype": ["Pure", "Sharpshooter"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Catch & Shoot (HoF)",
			"Upgradeable Badge 2": "Deep Range Deadeye (HoF)",
			"Upgradeable Badge 3": "Limitless Range (HoF)",
			"Upgradeable Badge 4": "Corner Specialist (HoF)",
			"Upgradeable Badge 5": "Tireless Scorer (Gold)",
			"H": 4,
			"G": 4,
			"S": 3,
			"B": 4,
			"T": 15
		},
		{
			"Archetype": ["Two-Way", "Sharpshooter"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Slashing", "Sharpshooter"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 9,
			"B": 6,
			"T": 22
		},
		{
			"Archetype": ["Playmaking", "Sharpshooter"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 5": "Tireless Scorer (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 5,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Sharpshooter"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 9,
			"B": 5,
			"T": 21
		},
		{
			"Archetype": ["Rebounding", "Sharpshooter"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Tireless Scorer (Silver)",
			"H": 0,
			"G": 7,
			"S": 7,
			"B": 8,
			"T": 22
		},
		{
			"Archetype": ["Shot Creating", "Sharpshooter"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 4": "Corner Specialist (Gold)",
			"Upgradeable Badge 5": "Tireless Scorer (Silver)",
			"Upgradeable Badge 1": "Catch & Shoot (Gold)",
			"Upgradeable Badge 2": "Deep Range Deadeye (Gold)",
			"Upgradeable Badge 3": "Limitless Range (Gold)",
			"H": 0,
			"G": 10,
			"S": 2,
			"B": 8,
			"T": 20
		},
	],
	"Defending": [
		{
			"Archetype": ["Sharpshooting", "Defender"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 2": "Pick Pocket (Gold)",
			"Upgradeable Badge 3": "Pick Dodger (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 6,
			"B": 8,
			"T": 22
		},
		{
			"Archetype": ["Lockdown", "Defender"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Defensive Stopper (HoF)",
			"Upgradeable Badge 2": "Pick Pocket (HoF)",
			"Upgradeable Badge 3": "Pick Dodger (HoF)",
			"Upgradeable Badge 4": "Charge Card (HoF)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 4,
			"G": 5,
			"S": 2,
			"B": 5,
			"T": 16
		},
		{
			"Archetype": ["Slashing", "Defender"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 2": "Pick Pocket (Gold)",
			"Upgradeable Badge 3": "Pick Dodger (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 5": "Posterizer (Gold)",
			"H": 0,
			"G": 10,
			"S": 4,
			"B": 3,
			"T": 17
		},
		{
			"Archetype": ["Playmaking", "Defender"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 2": "Pick Pocket (Gold)",
			"Upgradeable Badge 3": "Pick Dodger (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 5,
			"T": 22
		},
		{
			"Archetype": ["Post Scoring", "Defender"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 5": "Bruiser (HoF)",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 2": "Pick Pocket (Gold)",
			"Upgradeable Badge 3": "Pick Dodger (Gold)",
			"H": 1,
			"G": 7,
			"S": 6,
			"B": 6,
			"T": 20
		},
		{
			"Archetype": ["Rebounding", "Defender"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 5": "Bruiser (HoF)",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 3": "Pick Dodger (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 2": "Pick Pocket (Gold)",
			"H": 1,
			"G": 7,
			"S": 7,
			"B": 2,
			"T": 18
		},
		{
			"Archetype": ["Shot Creating", "Defender"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Defensive Stopper (Gold)",
			"Upgradeable Badge 4": "Charge Card (Gold)",
			"Upgradeable Badge 2": "Pick Pocket (Gold)",
			"Upgradeable Badge 3": "Pick Dodger (Gold)",
			"Upgradeable Badge 5": "Bruiser (Gold)",
			"H": 0,
			"G": 8,
			"S": 8,
			"B": 5,
			"T": 21
		},
	],
	"Driving & Finishing": [
		{
			"Archetype": ["Sharpshooting", "Slasher"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 1": "Posterizer (Gold)",
			"Upgradeable Badge 2": "Relentless Finisher (Gold)",
			"Upgradeable Badge 3": "Acrobat (Gold)",
			"Upgradeable Badge 4": "One Man Fastbreak (Gold)",
			"Upgradeable Badge 5": "Tear Dropper (Gold)",
			"H": 0,
			"G": 8,
			"S": 7,
			"B": 10,
			"T": 25
		},
		{
			"Archetype": ["Two-Way", "Slasher"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 1": "Posterizer (HoF)",
			"Upgradeable Badge 4": "One Man Fastbreak (HoF)",
			"Upgradeable Badge 3": "Acrobat (Gold)",
			"Upgradeable Badge 2": "Relentless Finisher (Gold)",
			"Upgradeable Badge 5": "Tear Dropper (Silver)",
			"H": 2,
			"G": 5,
			"S": 8,
			"B": 4,
			"T": 19
		},
		{
			"Archetype": ["Pure", "Slasher"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Posterizer (HoF)",
			"Upgradeable Badge 2": "Relentless Finisher (HoF)",
			"Upgradeable Badge 3": "Acrobat (HoF)",
			"Upgradeable Badge 4": "One Man Fastbreak (HoF)",
			"Upgradeable Badge 5": "Tear Dropper (Gold)",
			"H": 4,
			"G": 4,
			"S": 3,
			"B": 11,
			"T": 22
		},
		{
			"Archetype": ["Playmaking", "Slasher"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 4": "One Man Fastbreak (HoF)",
			"Upgradeable Badge 3": "Acrobat (HoF)",
			"Upgradeable Badge 2": "Relentless Finisher (Gold)",
			"Upgradeable Badge 1": "Posterizer (Gold)",
			"Upgradeable Badge 5": "Ankle Breaker (Gold)",
			"H": 2,
			"G": 6,
			"S": 8,
			"B": 5,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Slasher"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 3": "Acrobat (HoF)",
			"Upgradeable Badge 2": "Relentless Finisher (HoF)",
			"Upgradeable Badge 1": "Posterizer (Gold)",
			"Upgradeable Badge 4": "One Man Fastbreak (Gold)",
			"Upgradeable Badge 5": "Tear Dropper (Gold)",
			"H": 2,
			"G": 6,
			"S": 6,
			"B": 9,
			"T": 23
		},
		{
			"Archetype": ["Rebounding", "Slasher"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Posterizer (HoF)",
			"Upgradeable Badge 4": "One Man Fastbreak (HoF)",
			"Upgradeable Badge 2": "Relentless Finisher (Gold)",
			"Upgradeable Badge 3": "Acrobat (Gold)",
			"Upgradeable Badge 5": "Tear Dropper (Silver)",
			"H": 2,
			"G": 5,
			"S": 6,
			"B": 10,
			"T": 23
		},
		{
			"Archetype": ["Shot Creating", "Slasher"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 2": "Relentless Finisher (HoF)",
			"Upgradeable Badge 3": "Acrobat (HoF)",
			"Upgradeable Badge 4": "One Man Fastbreak (HoF)",
			"Upgradeable Badge 5": "Tear Dropper (Gold)",
			"Upgradeable Badge 1": "Posterizer (Gold)",
			"H": 3,
			"G": 5,
			"S": 6,
			"B": 8,
			"T": 22
		},
	],
	"Passing & Ball Handling": [
		{
			"Archetype": ["Sharpshooting", "Playmaker"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 4": "Flashy Passer (Gold)",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 1": "Ankle Breaker (Gold)",
			"Upgradeable Badge 5": "Pick & Roll Maestro (Gold)",
			"H": 0,
			"G": 8,
			"S": 9,
			"B": 5,
			"T": 22
		},
		{
			"Archetype": ["Two-Way", "Playmaker"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 1": "Ankle Breaker (Gold)",
			"Upgradeable Badge 5": "Pick & Roll Maestro (Gold)",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 4": "Flashy Passer (Gold)",
			"H": 0,
			"G": 9,
			"S": 6,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Slashing", "Playmaker"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Ankle Breaker (HoF)",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 4": "Flashy Passer (Gold)",
			"Upgradeable Badge 5": "One Man Fast Break (Gold)",
			"H": 1,
			"G": 9,
			"S": 5,
			"B": 5,
			"T": 20
		},
		{
			"Archetype": ["Pure", "Playmaker"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 2": "Dimer (HoF)",
			"Upgradeable Badge 1": "Ankle Breaker (HoF)",
			"Upgradeable Badge 5": "Pick & Roll Maestro (HoF)",
			"Upgradeable Badge 3": "Lob City Passer (HoF)",
			"Upgradeable Badge 4": "Flashy Passer (HoF)",
			"H": 5,
			"G": 5,
			"S": 3,
			"B": 6,
			"T": 19
		},
		{
			"Archetype": ["Post Scoring", "Playmaker"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 4": "Flashy Passer (Gold)",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 1": "Ankle Breaker (Gold)",
			"Upgradeable Badge 5": "Pick & Roll Maestro (Gold)",
			"H": 0,
			"G": 8,
			"S": 10,
			"B": 4,
			"T": 22
		},
		{
			"Archetype": ["Rebounding", "Playmaker"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 4": "Break Starter (Gold)",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 1": "Ankle Breaker (Gold)",
			"Upgradeable Badge 5": "Pick & Roll Maestro (Gold)",
			"H": 0,
			"G": 10,
			"S": 3,
			"B": 10,
			"T": 23
		},
		{
			"Archetype": ["Shot Creating", "Playmaker"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 1": "Ankle Breaker (HoF)",
			"Upgradeable Badge 2": "Dimer (Gold)",
			"Upgradeable Badge 3": "Lob City Passer (Gold)",
			"Upgradeable Badge 4": "Flashy Passer (Gold)",
			"Upgradeable Badge 5": "Pick & Roll Maestro (Gold)",
			"H": 1,
			"G": 10,
			"S": 4,
			"B": 5,
			"T": 20
		},
	],
	"Shot Creating": [
		{
			"Archetype": ["Sharpshooting", "Shot Creator"],
			"Secondary Skill": "3 Point Shooting",
			"Upgradeable Badge 4": "Difficult Shots (HoF)",
			"Upgradeable Badge 2": "Tireless Scorer (HoF)",
			"Upgradeable Badge 3": "Mid Range Deadeye (HoF)",
			"Upgradeable Badge 1": "Tear Dropper (Gold)",
			"Upgradeable Badge 5": "Corner Specialist (Silver)",
			"H": 3,
			"G": 4,
			"S": 7,
			"B": 9,
			"T": 23
		},
		{
			"Archetype": ["Two-Way", "Shot Creator"],
			"Secondary Skill": "Defending",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 1": "Tear Dropper (Gold)",
			"Upgradeable Badge 2": "Tireless Scorer (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "Ankle Breaker (Silver)",
			"H": 0,
			"G": 7,
			"S": 8,
			"B": 7,
			"T": 22
		},
		{
			"Archetype": ["Slashing", "Shot Creator"],
			"Secondary Skill": "Driving & Finishing",
			"Upgradeable Badge 1": "Tear Dropper (HoF)",
			"Upgradeable Badge 2": "Tireless Scorer (Gold)",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "Relentless Finisher (Gold)",
			"H": 1,
			"G": 10,
			"S": 1,
			"B": 10,
			"T": 22
		},
		{
			"Archetype": ["Playmaking", "Shot Creator"],
			"Secondary Skill": "Passing & Ball Handling",
			"Upgradeable Badge 2": "Tireless Scorer (HoF)",
			"Upgradeable Badge 4": "Difficult Shots (HoF)",
			"Upgradeable Badge 5": "Ankle Breaker (Gold)",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 1": "Tear Dropper (Gold)",
			"H": 2,
			"G": 6,
			"S": 7,
			"B": 6,
			"T": 21
		},
		{
			"Archetype": ["Post Scoring", "Shot Creator"],
			"Secondary Skill": "Post Scoring",
			"Upgradeable Badge 1": "Tear Dropper (HoF)",
			"Upgradeable Badge 2": "Tireless Scorer (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 5": "Up & Under Specialist (Gold)",
			"H": 1,
			"G": 8,
			"S": 5,
			"B": 7,
			"T": 21
		},
		{
			"Archetype": ["Rebounding", "Shot Creator"],
			"Secondary Skill": "Rebounding",
			"Upgradeable Badge 1": "Tear Dropper (Gold)",
			"Upgradeable Badge 3": "Mid Range Deadeye (Gold)",
			"Upgradeable Badge 2": "Tireless Scorer (Gold)",
			"Upgradeable Badge 4": "Difficult Shots (Gold)",
			"Upgradeable Badge 5": "Ankle Breaker (Silver)",
			"H": 0,
			"G": 7,
			"S": 7,
			"B": 11,
			"T": 25
		},
		{
			"Archetype": ["Pure", "Shot Creator"],
			"Secondary Skill": "Shot Creating",
			"Upgradeable Badge 3": "Mid Range Deadeye (HoF)",
			"Upgradeable Badge 1": "Tear Dropper (HoF)",
			"Upgradeable Badge 2": "Tireless Scorer (HoF)",
			"Upgradeable Badge 4": "Difficult Shots (HoF)",
			"Upgradeable Badge 5": "Ankle Breaker (Gold)",
			"H": 4,
			"G": 4,
			"S": 4,
			"B": 8,
			"T": 20
		},
	],
}

export default sg;