/* builder-styles.js */

import {Image, StyleSheet} from 'react-native';

const builderStyles = StyleSheet.create({
	container: {
		alignItems: 'stretch',
		backgroundColor: '#000',
		justifyContent: 'center',
		flex: 1,
		flexDirection: 'column',
	},
	headerContainer: {
		backgroundColor: '#000',
		height: 91,
		maxHeight: 91,
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
	},
	skillContainer: {
		flex: 1,
		flexWrap: 'wrap',
		flexDirection: 'row',
	},
	primaryText: {
		color: '#fff',
		fontSize: 48,
		fontWeight: '700',
		textAlign: 'center',
		paddingBottom: -10,
	},
	secondaryText: {
		color: '#fff',
		fontSize: 20,
		fontWeight: '100',
		textAlign: 'center',
	},
	contentContainer: {
		flex: 2,
		flexDirection: 'column',
		backgroundColor: '#000',
	},
	cypContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'stretch',
		justifyContent: 'center',
		position: 'relative',
	},
	positionText: {
		color: '#fff',
		fontSize: 32,
		fontWeight: '900',
		textAlign: 'center',
		position: 'absolute',
		top: -10,
		left: 0,
		flex: 1,
		zIndex: 100,
	},
	cypImage: {
		alignItems: 'flex-start',
		resizeMode: Image.resizeMode.contain,
		justifyContent: 'flex-start',
		alignSelf: 'center',
		flex: 1,
	},
	scrollContainer: {
		flex: 1,
		flexDirection: 'column',
	},
	builderHeader: {
		fontSize: 24,
		fontWeight: '700',
		marginBottom: 16,
		textAlign: 'center',
	},
	builderButton: {
		width: 130,
		backgroundColor: '#c4b301',
		elevation: 1.5,
		height: 50,
		alignItems: 'center',
		alignSelf: 'flex-end',
		justifyContent: 'center',
	},
	builderButtonText: {
		color: '#fff',
		fontSize: 22,
		textAlign: 'center',
		textAlignVertical: 'center',
	},
	boldLabel: {
		fontWeight: '700',
	},
	sidebar: {
		alignItems: 'flex-start',
		backgroundColor: '#464646',
		justifyContent: 'flex-start',
		flex: 1,
		flexDirection: 'column',
	},
	closeButton: {
		margin: 8,
		position: 'absolute',
		top: 0,
		right: 8,
	},
	sbProfileName: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 8,
		paddingTop: 16,
		paddingBottom: 16,
	},
	sbProfileText: {
		color: '#fff',
		fontSize: 18,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbFeaturedContent: {
		alignItems: 'flex-start',
		alignSelf: 'stretch',
		backgroundColor: '#3e355c',
		borderTopWidth: 1,
		borderTopColor: '#96afd1',
		borderBottomWidth: 1,
		borderBottomColor: '#444',
		flexDirection: 'column',
		justifyContent: 'flex-start',
		padding: 8,
		paddingBottom: 16,
	},
	sbHeader: {
		color: '#fff',
		fontSize: 16,
		fontWeight: '100',
		marginLeft: 8,
	},
	sbSubHeader: {
		color: '#fff',
		fontSize: 14,
		fontWeight: '100',
		marginLeft: 8,
	},
	menuButton: {
		position: 'absolute',
		top: 25,
		left: 10,
		zIndex: 100,
	},
	menuItems: {
		flex: 6,
		flexDirection: 'column',
	},
	menuItem: {
		alignSelf: 'stretch',
		padding: 16,
	},
	menuHeader: {
		color: '#fff',
		fontSize: 28,
		fontWeight: '100',
	},
	menuLabel: {
		color: '#fff',
		fontSize: 18,
		fontWeight: '100',
	},
	sbFooter: {
		alignSelf: 'stretch',
		alignItems: 'flex-end',
		borderTopWidth: 1,
		borderTopColor: '#96afd1',
		flex: 1,
		flexDirection: 'row',
		justifyContent: 'flex-start',
		padding: 16,
	},
	versionText: {
		alignSelf: 'flex-end',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
		bottom: 12,
		right: 12,
		color: '#fff',
		position: 'absolute',
		fontSize: 12,
		opacity: 0.75,
	},
	skillPanel: {
		flex: 0.5,
		flexDirection: 'column',
		flexWrap: 'wrap',
		justifyContent: 'center',
	},
	skillText: {
		color: '#fff',
		fontSize: 12,
		fontWeight: '100',
		textAlign: 'center',
	}
});

export default builderStyles;
